/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package colegio.vistas;
import colegio.Alumno;
import colegio.Materia;
import java.util.HashSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class Colegio extends javax.swing.JFrame {
    public static HashSet<Alumno> alumnos = new HashSet<>();
    public static HashSet<Materia> materias = new HashSet<>();

    /**
     * Creates new form Colegio
     */
    public Colegio() {
        initComponents();
        escritorio.setLayout(null);  
        // Configurar tamaños y posiciones de los JInternalFrames
        jInternalFrameAlumno.setBounds(50, 50, 450, 300);
        jInternalFrameMateria.setBounds(50, 50, 450, 300);
        jInternalFrameInscripcion.setBounds(50, 50, 400, 300);
        
        jInternalFrameAlumno.setDefaultCloseOperation(javax.swing.JInternalFrame.HIDE_ON_CLOSE);
        jInternalFrameMateria.setDefaultCloseOperation(javax.swing.JInternalFrame.HIDE_ON_CLOSE);
        jInternalFrameInscripcion.setDefaultCloseOperation(javax.swing.JInternalFrame.HIDE_ON_CLOSE);
    
        // Hacer los frames redimensionables, cerrables, etc.
        jInternalFrameAlumno.setClosable(true);
        jInternalFrameAlumno.setMaximizable(true);
        jInternalFrameAlumno.setIconifiable(true);
        jInternalFrameAlumno.setResizable(true);
        
        jInternalFrameMateria.setClosable(true);
        jInternalFrameMateria.setMaximizable(true);
        jInternalFrameMateria.setIconifiable(true);
        jInternalFrameMateria.setResizable(true);
        
        jInternalFrameInscripcion.setClosable(true);
        jInternalFrameInscripcion.setMaximizable(true);
        jInternalFrameInscripcion.setIconifiable(true);
        jInternalFrameInscripcion.setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jInternalFrameMateria = new javax.swing.JInternalFrame();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jInternalFrameAlumno = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        legajoLabel = new javax.swing.JLabel();
        apellidoLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        guardarAlumo = new javax.swing.JButton();
        nuevoAlumno = new javax.swing.JButton();
        salirAlumno = new javax.swing.JButton();
        legajoInput = new javax.swing.JTextField();
        apellidoInput = new javax.swing.JTextField();
        nombreInput = new javax.swing.JTextField();
        jInternalFrameInscripcion = new javax.swing.JInternalFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        alumnoMenu = new javax.swing.JMenu();
        menuItemAlumno = new javax.swing.JMenuItem();
        materiaMenu = new javax.swing.JMenu();
        menuItemMateria = new javax.swing.JMenuItem();
        registroMenu = new javax.swing.JMenu();
        jMenuItemRegistro = new javax.swing.JMenuItem();
        salirMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrameMateria.setIconifiable(true);
        jInternalFrameMateria.setMaximizable(true);
        jInternalFrameMateria.setResizable(true);
        jInternalFrameMateria.setTitle("Materia");
        jInternalFrameMateria.setNormalBounds(new java.awt.Rectangle(50, 50, 400, 250));
        jInternalFrameMateria.setVisible(false);

        jLabel5.setText("Formulario de materias");

        jLabel6.setText("CODIGO DE MATERIA:");

        jLabel7.setText("NOMBRE DE LA MATERIA:");

        jLabel8.setText("AÑO AL QUE PERTENECE");

        jTextField4.setText("jTextField4");

        jTextField5.setText("jTextField5");

        jTextField6.setText("jTextField6");

        jButton4.setText("Guardar");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Nuevo");

        jButton6.setText("Salir");

        javax.swing.GroupLayout jInternalFrameMateriaLayout = new javax.swing.GroupLayout(jInternalFrameMateria.getContentPane());
        jInternalFrameMateria.getContentPane().setLayout(jInternalFrameMateriaLayout);
        jInternalFrameMateriaLayout.setHorizontalGroup(
            jInternalFrameMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameMateriaLayout.createSequentialGroup()
                .addGroup(jInternalFrameMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrameMateriaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jInternalFrameMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrameMateriaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(56, 56, 56)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrameMateriaLayout.createSequentialGroup()
                                .addGroup(jInternalFrameMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(35, 35, 35)
                                .addGroup(jInternalFrameMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jInternalFrameMateriaLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(jInternalFrameMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrameMateriaLayout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6))
                            .addComponent(jLabel5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrameMateriaLayout.setVerticalGroup(
            jInternalFrameMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameMateriaLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(35, 35, 35)
                .addGroup(jInternalFrameMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrameMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        jInternalFrameAlumno.setIconifiable(true);
        jInternalFrameAlumno.setMaximizable(true);
        jInternalFrameAlumno.setResizable(true);
        jInternalFrameAlumno.setEnabled(false);
        jInternalFrameAlumno.setNormalBounds(new java.awt.Rectangle(50, 50, 400, 350));
        jInternalFrameAlumno.setVisible(false);

        jLabel1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Formulario de alumnos");

        legajoLabel.setText("LEGAJO");

        apellidoLabel.setText("APELLIDO");

        nombreLabel.setText("NOMBRE");

        guardarAlumo.setText("Guardar");
        guardarAlumo.setEnabled(false);
        guardarAlumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarAlumoActionPerformed(evt);
            }
        });

        nuevoAlumno.setText("Nuevo");
        nuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoAlumnoActionPerformed(evt);
            }
        });

        salirAlumno.setText("Salir");
        salirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirAlumnoActionPerformed(evt);
            }
        });

        legajoInput.setEnabled(false);
        legajoInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                legajoInputFocusLost(evt);
            }
        });
        legajoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                legajoInputActionPerformed(evt);
            }
        });

        apellidoInput.setEnabled(false);
        apellidoInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                apellidoInputFocusLost(evt);
            }
        });
        apellidoInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoInputActionPerformed(evt);
            }
        });

        nombreInput.setEnabled(false);
        nombreInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreInputFocusLost(evt);
            }
        });
        nombreInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrameAlumnoLayout = new javax.swing.GroupLayout(jInternalFrameAlumno.getContentPane());
        jInternalFrameAlumno.getContentPane().setLayout(jInternalFrameAlumnoLayout);
        jInternalFrameAlumnoLayout.setHorizontalGroup(
            jInternalFrameAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(legajoLabel)
                    .addComponent(apellidoLabel)
                    .addComponent(nombreLabel))
                .addGap(43, 43, 43)
                .addGroup(jInternalFrameAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreInput)
                    .addComponent(apellidoInput)
                    .addGroup(jInternalFrameAlumnoLayout.createSequentialGroup()
                        .addComponent(legajoInput, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(119, 119, 119))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameAlumnoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(guardarAlumo)
                .addGap(18, 18, 18)
                .addComponent(nuevoAlumno)
                .addGap(18, 18, 18)
                .addComponent(salirAlumno)
                .addGap(16, 16, 16))
            .addGroup(jInternalFrameAlumnoLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrameAlumnoLayout.setVerticalGroup(
            jInternalFrameAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameAlumnoLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(jInternalFrameAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(legajoLabel)
                    .addComponent(legajoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoLabel)
                    .addComponent(apellidoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(jInternalFrameAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarAlumo)
                    .addComponent(nuevoAlumno)
                    .addComponent(salirAlumno))
                .addContainerGap())
        );

        jInternalFrameInscripcion.setClosable(true);
        jInternalFrameInscripcion.setIconifiable(true);
        jInternalFrameInscripcion.setMaximizable(true);
        jInternalFrameInscripcion.setResizable(true);
        jInternalFrameInscripcion.setNormalBounds(new java.awt.Rectangle(50, 50, 400, 250));
        jInternalFrameInscripcion.setVisible(false);

        jLabel9.setText("Formulario de Inscripción");

        jLabel10.setText("ELIJA UNA MATERIA:");

        jLabel11.setText("ELIJA UN ALUMNO:");

        jButton7.setText("Inscribir");
        jButton7.setEnabled(false);

        jButton8.setText("Salir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jInternalFrameInscripcionLayout = new javax.swing.GroupLayout(jInternalFrameInscripcion.getContentPane());
        jInternalFrameInscripcion.getContentPane().setLayout(jInternalFrameInscripcionLayout);
        jInternalFrameInscripcionLayout.setHorizontalGroup(
            jInternalFrameInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameInscripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrameInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(33, 33, 33)
                .addGroup(jInternalFrameInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox1, 0, 213, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrameInscripcionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(29, 29, 29)
                .addComponent(jButton8)
                .addGap(19, 19, 19))
        );
        jInternalFrameInscripcionLayout.setVerticalGroup(
            jInternalFrameInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrameInscripcionLayout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(33, 33, 33)
                .addGroup(jInternalFrameInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrameInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrameInscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap())
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        escritorio.setLayer(jInternalFrameMateria, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jInternalFrameAlumno, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jInternalFrameInscripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
<<<<<<< HEAD
                .addGap(83, 83, 83)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                        .addComponent(jInternalFrameMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227))
                    .addGroup(escritorioLayout.createSequentialGroup()
                        .addComponent(jInternalFrameInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
=======
                .addGap(316, 316, 316)
                .addComponent(jInternalFrameInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(298, Short.MAX_VALUE))
>>>>>>> 9c373c9d40a77bac20f7d8e5af5952b0593ea815
            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(escritorioLayout.createSequentialGroup()
                    .addGap(400, 400, 400)
                    .addComponent(jInternalFrameAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(551, Short.MAX_VALUE)))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jInternalFrameInscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInternalFrameMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
            .addGroup(escritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(escritorioLayout.createSequentialGroup()
                    .addGap(400, 400, 400)
                    .addComponent(jInternalFrameAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(368, Short.MAX_VALUE)))
        );

        alumnoMenu.setText("Alumno");

        menuItemAlumno.setText("Agregar Alumno");
        menuItemAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAlumnoActionPerformed(evt);
            }
        });
        alumnoMenu.add(menuItemAlumno);

        jMenuBar1.add(alumnoMenu);

        materiaMenu.setText("Materia");

        menuItemMateria.setText("Agregar Materia");
        menuItemMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMateriaActionPerformed(evt);
            }
        });
        materiaMenu.add(menuItemMateria);

        jMenuBar1.add(materiaMenu);

        registroMenu.setText("Registro");

        jMenuItemRegistro.setText("Agregar Inscripción");
        jMenuItemRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistroActionPerformed(evt);
            }
        });
        registroMenu.add(jMenuItemRegistro);

        jMenuBar1.add(registroMenu);

        salirMenu.setText("Salir");
        jMenuBar1.add(salirMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAlumnoActionPerformed
        jInternalFrameMateria.setVisible(false);
        jInternalFrameInscripcion.setVisible(false);
        jInternalFrameAlumno.toFront();
        jInternalFrameAlumno.setVisible(true);
    }//GEN-LAST:event_menuItemAlumnoActionPerformed

    private void menuItemMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMateriaActionPerformed
        jInternalFrameInscripcion.setVisible(false);
        jInternalFrameAlumno.setVisible(false);
        jInternalFrameMateria.toFront();  // Agregar esta línea
        jInternalFrameMateria.setVisible(true);
    }//GEN-LAST:event_menuItemMateriaActionPerformed

    private void jMenuItemRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistroActionPerformed
        jInternalFrameAlumno.setVisible(false);
        jInternalFrameMateria.setVisible(false);
        jInternalFrameInscripcion.toFront();  // Agregar esta línea
        jInternalFrameInscripcion.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistroActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void guardarAlumoActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // Validar que los campos no estén vacíos
            if (legajoInput.getText().isEmpty() || 
                apellidoInput.getText().isEmpty() || 
                nombreInput.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Complete todos los campos", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int legajo = Integer.parseInt(legajoInput.getText());
            String apellido = apellidoInput.getText().trim();
            String nombre = nombreInput.getText().trim();
            
            Alumno nuevoAlumno = new Alumno(legajo, apellido, nombre);
            
            
            if (alumnos.add(nuevoAlumno)) {
                JOptionPane.showMessageDialog(this, "Alumno guardado correctamente", 
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

                limpiarInputsAlumno();
                desactivarCamposAlumno();
                guardarAlumo.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Ya existe un alumno con ese legajo", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                legajoInput.requestFocus();
            }
            
            System.out.println(alumnos);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El legajo debe ser un número válido", 
                "Error", JOptionPane.ERROR_MESSAGE);
            legajoInput.requestFocus();
        }
    }                                            

    private void salirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirAlumnoActionPerformed
        limpiarInputsAlumno();
        desactivarCamposAlumno();
        guardarAlumo.setEnabled(false);
        jInternalFrameAlumno.setVisible(false);
       
    }//GEN-LAST:event_salirAlumnoActionPerformed

    private void legajoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_legajoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_legajoInputActionPerformed

    private void apellidoInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoInputActionPerformed

    private void nombreInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreInputActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

    }//GEN-LAST:event_jButton8ActionPerformed

    private void nuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoAlumnoActionPerformed
        activarCamposAlumno();
        guardarAlumo.setEnabled(true);
    }//GEN-LAST:event_nuevoAlumnoActionPerformed

    private void legajoInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_legajoInputFocusLost
        String val= "[0-9]*";
        if(!legajoInput.getText().matches(val) || legajoInput.getText().length() == 0 ){
            JOptionPane.showMessageDialog(this, "Debe ingresar solo números y no puede estar vacío!");
            legajoInput.requestFocus();
        }
    }//GEN-LAST:event_legajoInputFocusLost

    private void apellidoInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_apellidoInputFocusLost
        if(apellidoInput.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "El apellido no puede estar vacio!");
            apellidoInput.requestFocus();
        }
    }//GEN-LAST:event_apellidoInputFocusLost

    private void nombreInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreInputFocusLost
        if(nombreInput.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "El nombre no puede estar vacio!");
            nombreInput.requestFocus();
        }
    }//GEN-LAST:event_nombreInputFocusLost
    

    
    private void activarCamposAlumno(){
        legajoInput.setEnabled(true);
        apellidoInput.setEnabled(true);
        nombreInput.setEnabled(true);
    }
    
    private void desactivarCamposAlumno(){
        legajoInput.setEnabled(false);
        apellidoInput.setEnabled(false);
        nombreInput.setEnabled(false);
    }
    private void limpiarInputsAlumno(){
        legajoInput.setText("");
        apellidoInput.setText("");
        nombreInput.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colegio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colegio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu alumnoMenu;
    private javax.swing.JTextField apellidoInput;
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton guardarAlumo;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrameAlumno;
    private javax.swing.JInternalFrame jInternalFrameInscripcion;
    private javax.swing.JInternalFrame jInternalFrameMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemRegistro;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField legajoInput;
    private javax.swing.JLabel legajoLabel;
    private javax.swing.JMenu materiaMenu;
    private javax.swing.JMenuItem menuItemAlumno;
    private javax.swing.JMenuItem menuItemMateria;
    private javax.swing.JTextField nombreInput;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JButton nuevoAlumno;
    private javax.swing.JMenu registroMenu;
    private javax.swing.JButton salirAlumno;
    private javax.swing.JMenu salirMenu;
    // End of variables declaration//GEN-END:variables
}
